/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClickMidiaRouteImport } from './routes/click-midia'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClickMidiaRoute = ClickMidiaRouteImport.update({
  id: '/click-midia',
  path: '/click-midia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/click-midia': typeof ClickMidiaRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/click-midia': typeof ClickMidiaRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/click-midia': typeof ClickMidiaRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/click-midia' | '/quem-somos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/click-midia' | '/quem-somos'
  id: '__root__' | '/' | '/click-midia' | '/quem-somos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClickMidiaRoute: typeof ClickMidiaRoute
  QuemSomosRoute: typeof QuemSomosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/click-midia': {
      id: '/click-midia'
      path: '/click-midia'
      fullPath: '/click-midia'
      preLoaderRoute: typeof ClickMidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClickMidiaRoute: ClickMidiaRoute,
  QuemSomosRoute: QuemSomosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
